name: Integration Tests with Service Container

on:
  push:
    branches: [main]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/simple-web-app:latest .
          docker push ghcr.io/${{ github.repository_owner }}/simple-web-app:latest

  integration-test:
    needs: build-and-publish
    runs-on: ubuntu-latest
    services:
      app:
        image: ghcr.io/${{ github.repository_owner || 'abhipatel18' }}/simple-web-app:latest
        ports:
          - 3000:3000
        options: >-
          --health-cmd="curl http://localhost:3000/health || exit 1"
          --health-interval=10s
          --health-retries=5

    steps:
      - name: Wait for app
        run: sleep 20

      - name: Run integration test
        run: curl -f http://localhost:3000/health


    permissions:
        packages: write
        contents: read
